// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: proto/Tracker.proto

package omggolib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_Unknown Side = 0
	Side_Buy     Side = 1
	Side_Sell    Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "Unknown",
		1: "Buy",
		2: "Sell",
	}
	Side_value = map[string]int32{
		"Unknown": 0,
		"Buy":     1,
		"Sell":    2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Tracker_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_proto_Tracker_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{0}
}

type SubscriptionStatus int32

const (
	SubscriptionStatus_StatusUnknown    SubscriptionStatus = 0
	SubscriptionStatus_StatusCompleted  SubscriptionStatus = 1
	SubscriptionStatus_StatusProcessing SubscriptionStatus = 2
	SubscriptionStatus_StatusFailed     SubscriptionStatus = 3
	SubscriptionStatus_StatusTimeout    SubscriptionStatus = 4
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "StatusUnknown",
		1: "StatusCompleted",
		2: "StatusProcessing",
		3: "StatusFailed",
		4: "StatusTimeout",
	}
	SubscriptionStatus_value = map[string]int32{
		"StatusUnknown":    0,
		"StatusCompleted":  1,
		"StatusProcessing": 2,
		"StatusFailed":     3,
		"StatusTimeout":    4,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Tracker_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_proto_Tracker_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{1}
}

type TrackResult int32

const (
	TrackResult_ResultUnknown              TrackResult = 0
	TrackResult_ResultOK                   TrackResult = 1
	TrackResult_ResultFailed               TrackResult = 2
	TrackResult_ResultAlreadySubscribed    TrackResult = 3
	TrackResult_ResultWrongWalletPublicKey TrackResult = 4
)

// Enum value maps for TrackResult.
var (
	TrackResult_name = map[int32]string{
		0: "ResultUnknown",
		1: "ResultOK",
		2: "ResultFailed",
		3: "ResultAlreadySubscribed",
		4: "ResultWrongWalletPublicKey",
	}
	TrackResult_value = map[string]int32{
		"ResultUnknown":              0,
		"ResultOK":                   1,
		"ResultFailed":               2,
		"ResultAlreadySubscribed":    3,
		"ResultWrongWalletPublicKey": 4,
	}
)

func (x TrackResult) Enum() *TrackResult {
	p := new(TrackResult)
	*p = x
	return p
}

func (x TrackResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Tracker_proto_enumTypes[2].Descriptor()
}

func (TrackResult) Type() protoreflect.EnumType {
	return &file_proto_Tracker_proto_enumTypes[2]
}

func (x TrackResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackResult.Descriptor instead.
func (TrackResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{2}
}

type SubscribeTransactionInfoStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeTransactionInfoStreamRequest) Reset() {
	*x = SubscribeTransactionInfoStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTransactionInfoStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTransactionInfoStreamRequest) ProtoMessage() {}

func (x *SubscribeTransactionInfoStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTransactionInfoStreamRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTransactionInfoStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{0}
}

type TransactionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mint            string  `protobuf:"bytes,1,opt,name=Mint,proto3" json:"Mint,omitempty"`
	TransactionSide Side    `protobuf:"varint,2,opt,name=TransactionSide,proto3,enum=tracker.Side" json:"TransactionSide,omitempty"`
	Amount          float64 `protobuf:"fixed64,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Balance         float64 `protobuf:"fixed64,4,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Hash            string  `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfo) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *TransactionInfo) GetTransactionSide() Side {
	if x != nil {
		return x.TransactionSide
	}
	return Side_Unknown
}

func (x *TransactionInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *TransactionInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TransactionInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string             `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ChatId    int64              `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	Status    SubscriptionStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=tracker.SubscriptionStatus" json:"Status,omitempty"`
	Info      *TransactionInfo   `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *TransactionInfoResponse) Reset() {
	*x = TransactionInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Tracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfoResponse) ProtoMessage() {}

func (x *TransactionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Tracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfoResponse.ProtoReflect.Descriptor instead.
func (*TransactionInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionInfoResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionInfoResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TransactionInfoResponse) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_StatusUnknown
}

func (x *TransactionInfoResponse) GetInfo() *TransactionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type TrackedAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId      string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ChatId         int64  `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	TrackedAccount string `protobuf:"bytes,3,opt,name=TrackedAccount,proto3" json:"TrackedAccount,omitempty"`
}

func (x *TrackedAccountRequest) Reset() {
	*x = TrackedAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Tracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackedAccountRequest) ProtoMessage() {}

func (x *TrackedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Tracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackedAccountRequest.ProtoReflect.Descriptor instead.
func (*TrackedAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{3}
}

func (x *TrackedAccountRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TrackedAccountRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TrackedAccountRequest) GetTrackedAccount() string {
	if x != nil {
		return x.TrackedAccount
	}
	return ""
}

type TrackedAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId     string      `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ChatId        int64       `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	Result        TrackResult `protobuf:"varint,3,opt,name=Result,proto3,enum=tracker.TrackResult" json:"Result,omitempty"`
	ResultMessage string      `protobuf:"bytes,4,opt,name=ResultMessage,proto3" json:"ResultMessage,omitempty"`
}

func (x *TrackedAccountResponse) Reset() {
	*x = TrackedAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Tracker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackedAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackedAccountResponse) ProtoMessage() {}

func (x *TrackedAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Tracker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackedAccountResponse.ProtoReflect.Descriptor instead.
func (*TrackedAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_Tracker_proto_rawDescGZIP(), []int{4}
}

func (x *TrackedAccountResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TrackedAccountResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TrackedAccountResponse) GetResult() TrackResult {
	if x != nil {
		return x.Result
	}
	return TrackResult_ResultUnknown
}

func (x *TrackedAccountResponse) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

var File_proto_Tracker_proto protoreflect.FileDescriptor

var file_proto_Tracker_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x27,
	0x0a, 0x25, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4d,
	0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x69, 0x6e, 0x74, 0x12,
	0x37, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0xb2,
	0x01, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x75, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0x26, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x65, 0x6c, 0x6c, 0x10, 0x02, 0x2a, 0x77, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x04,
	0x2a, 0x7d, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x11, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x6c, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x10, 0x03, 0x12,
	0x1e, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x57, 0x72, 0x6f, 0x6e, 0x67, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x10, 0x04, 0x32,
	0xdb, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6b, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x2e, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x5c, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x6f, 0x6d, 0x67, 0x67, 0x6f, 0x6c, 0x69, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Tracker_proto_rawDescOnce sync.Once
	file_proto_Tracker_proto_rawDescData = file_proto_Tracker_proto_rawDesc
)

func file_proto_Tracker_proto_rawDescGZIP() []byte {
	file_proto_Tracker_proto_rawDescOnce.Do(func() {
		file_proto_Tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Tracker_proto_rawDescData)
	})
	return file_proto_Tracker_proto_rawDescData
}

var file_proto_Tracker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_Tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_Tracker_proto_goTypes = []any{
	(Side)(0),               // 0: tracker.Side
	(SubscriptionStatus)(0), // 1: tracker.SubscriptionStatus
	(TrackResult)(0),        // 2: tracker.TrackResult
	(*SubscribeTransactionInfoStreamRequest)(nil), // 3: tracker.SubscribeTransactionInfoStreamRequest
	(*TransactionInfo)(nil),                       // 4: tracker.TransactionInfo
	(*TransactionInfoResponse)(nil),               // 5: tracker.TransactionInfoResponse
	(*TrackedAccountRequest)(nil),                 // 6: tracker.TrackedAccountRequest
	(*TrackedAccountResponse)(nil),                // 7: tracker.TrackedAccountResponse
}
var file_proto_Tracker_proto_depIdxs = []int32{
	0, // 0: tracker.TransactionInfo.TransactionSide:type_name -> tracker.Side
	1, // 1: tracker.TransactionInfoResponse.Status:type_name -> tracker.SubscriptionStatus
	4, // 2: tracker.TransactionInfoResponse.Info:type_name -> tracker.TransactionInfo
	2, // 3: tracker.TrackedAccountResponse.Result:type_name -> tracker.TrackResult
	3, // 4: tracker.TrackerService.SubscribeTransactions:input_type -> tracker.SubscribeTransactionInfoStreamRequest
	6, // 5: tracker.TrackerService.SendTrackedAccountRequest:input_type -> tracker.TrackedAccountRequest
	5, // 6: tracker.TrackerService.SubscribeTransactions:output_type -> tracker.TransactionInfoResponse
	7, // 7: tracker.TrackerService.SendTrackedAccountRequest:output_type -> tracker.TrackedAccountResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_Tracker_proto_init() }
func file_proto_Tracker_proto_init() {
	if File_proto_Tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Tracker_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeTransactionInfoStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Tracker_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TransactionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Tracker_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TransactionInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Tracker_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TrackedAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Tracker_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TrackedAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Tracker_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Tracker_proto_goTypes,
		DependencyIndexes: file_proto_Tracker_proto_depIdxs,
		EnumInfos:         file_proto_Tracker_proto_enumTypes,
		MessageInfos:      file_proto_Tracker_proto_msgTypes,
	}.Build()
	File_proto_Tracker_proto = out.File
	file_proto_Tracker_proto_rawDesc = nil
	file_proto_Tracker_proto_goTypes = nil
	file_proto_Tracker_proto_depIdxs = nil
}
